# Generated by Django 4.1 on 2022-08-29 11:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_userreservationform_userreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Incorrect email', regex='^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$')]),
        ),
        migrations.AddField(
            model_name='userreservation',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
