# Generated by Django 4.1 on 2022-08-29 11:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userreservation_email_userreservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Incorrect email', regex="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")]),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
