# Generated by Django 4.1 on 2022-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_userreservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.DateField(),
        ),
    ]
