# Generated by Django 4.1 on 2022-08-29 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_userreservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Incorrect date', regex='^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[13-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$')]),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='time',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Incorrect time', regex='^(?:[01]?\\d|2[0-3])(?::[0-5]\\d){1,2}$')]),
        ),
    ]
