# Generated by Django 4.1 on 2022-08-29 17:45

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_userreservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.Chefs.get_file_name)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('position', models.SmallIntegerField(unique=True)),
                ('insta_link', models.CharField(blank=True, max_length=100)),
                ('twitter_link', models.CharField(blank=True, max_length=100)),
                ('facebook_link', models.CharField(blank=True, max_length=100)),
                ('linked_link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
