# Generated by Django 4.1 on 2022-08-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_chefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
