# Generated by Django 4.1 on 2022-08-30 09:25

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('paragraph_1', models.CharField(blank=True, max_length=200)),
                ('paragraph_2', models.CharField(blank=True, max_length=200)),
                ('paragraph_3', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to=base.models.AboutUs.get_file_name)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
