# Generated by Django 4.1 on 2022-08-30 10:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.Testimonials.get_file_name)),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('stars', models.SmallIntegerField()),
                ('review', models.TextField(max_length=200)),
            ],
        ),
    ]
