# Generated by Django 4.1 on 2022-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
